//! Hygiene checks across the fixture / dataset catalog.
//!
//! Phase 2 starting set: assert that `comparison/manifest.json` is byte-equal
//! to the manifest derived from `datasets::iter_cases()`. Phase 5 will extend
//! this file with re-fit tolerance checks, golden provenance assertions, and
//! the levels.txt ↔ meta.toml schema lint.
//!
//! When this test fails, the fix is almost always:
//!
//!   cargo run --release --example compare_rust
//!
//! which regenerates `comparison/manifest.json` from the registry.

use std::fs;
use std::path::PathBuf;

use mixedmodels::datasets;
use serde_json::{json, Value};

fn comparison_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("comparison")
}

/// Build the manifest JSON exactly as `examples/compare_rust.rs` writes it.
/// Keep this in sync with the writer: any change there must mirror here.
fn derived_manifest() -> Value {
    let fits: Vec<Value> = datasets::iter_cases()
        .map(|case| {
            json!({
                "dataset": case.name,
                "estimator": case.fit.estimator,
                "family": case.fit.family,
                "formula": case.fit.formula,
                "link": case.fit.link,
                "weights": case.fit.weights,
            })
        })
        .collect();
    json!({ "fits": fits })
}

#[test]
fn comparison_manifest_matches_registry_derived() {
    let manifest_path = comparison_root().join("manifest.json");
    if !manifest_path.exists() {
        // Manifest is regenerated by `compare_rust`. If it's absent (e.g. on a
        // fresh checkout where the example was never run), the test is a no-op
        // — derivation correctness is still asserted by the unit tests on
        // `iter_cases`. Fail visibly so a CI runner notices the gap rather
        // than silently skipping.
        panic!(
            "comparison/manifest.json missing — run `cargo run --release --example compare_rust` to regenerate"
        );
    }
    let on_disk: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path)
            .unwrap_or_else(|e| panic!("read {manifest_path:?}: {e}")),
    )
    .expect("parse manifest.json");

    let derived = derived_manifest();

    if on_disk != derived {
        // Show a focused diff of the `fits` arrays so the failure message is
        // actionable. The full JSON would be a wall of text.
        let on_disk_fits = on_disk.get("fits").and_then(|v| v.as_array()).cloned().unwrap_or_default();
        let derived_fits = derived.get("fits").and_then(|v| v.as_array()).cloned().unwrap_or_default();
        let only_in_disk: Vec<&Value> = on_disk_fits.iter().filter(|v| !derived_fits.contains(v)).collect();
        let only_in_derived: Vec<&Value> = derived_fits.iter().filter(|v| !on_disk_fits.contains(v)).collect();
        panic!(
            "comparison/manifest.json drifted from registry-derived manifest.\n\n\
             only in manifest.json ({}):\n{}\n\n\
             only in registry-derived ({}):\n{}\n\n\
             To fix: cargo run --release --example compare_rust",
            only_in_disk.len(),
            serde_json::to_string_pretty(&only_in_disk).unwrap_or_default(),
            only_in_derived.len(),
            serde_json::to_string_pretty(&only_in_derived).unwrap_or_default(),
        );
    }
}
