//! Hygiene checks across the fixture / dataset catalog.
//!
//! Phase 2: comparison/manifest.json must equal the registry-derived view.
//! Phase 4: every JSON golden under tests/fixtures/{compiler_contract,parity}/
//!          must have a sibling `<stem>.provenance.json`.
//! Phase 5 (future) will add re-fit tolerance checks and the
//! levels.txt ↔ meta.toml schema lint.
//!
//! When the manifest test fails, regenerate via:
//!     cargo run --release --example compare_rust
//!
//! When the provenance test fails on a fresh checkout (no goldens regenerated yet):
//!     cargo run --example backfill_fixture_provenance

use std::fs;
use std::path::{Path, PathBuf};

use mixedmodels::datasets;
use serde_json::{json, Value};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn comparison_root() -> PathBuf {
    repo_root().join("comparison")
}

/// Build the manifest JSON exactly as `examples/compare_rust.rs` writes it.
/// Keep this in sync with the writer: any change there must mirror here.
fn derived_manifest() -> Value {
    let fits: Vec<Value> = datasets::iter_cases()
        .map(|case| {
            json!({
                "dataset": case.name,
                "estimator": case.fit.estimator,
                "family": case.fit.family,
                "formula": case.fit.formula,
                "link": case.fit.link,
                "weights": case.fit.weights,
            })
        })
        .collect();
    json!({ "fits": fits })
}

#[test]
fn comparison_manifest_matches_registry_derived() {
    let manifest_path = comparison_root().join("manifest.json");
    if !manifest_path.exists() {
        // Manifest is regenerated by `compare_rust`. If it's absent (e.g. on a
        // fresh checkout where the example was never run), the test is a no-op
        // — derivation correctness is still asserted by the unit tests on
        // `iter_cases`. Fail visibly so a CI runner notices the gap rather
        // than silently skipping.
        panic!(
            "comparison/manifest.json missing — run `cargo run --release --example compare_rust` to regenerate"
        );
    }
    let on_disk: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path)
            .unwrap_or_else(|e| panic!("read {manifest_path:?}: {e}")),
    )
    .expect("parse manifest.json");

    let derived = derived_manifest();

    if on_disk != derived {
        // Show a focused diff of the `fits` arrays so the failure message is
        // actionable. The full JSON would be a wall of text.
        let on_disk_fits = on_disk.get("fits").and_then(|v| v.as_array()).cloned().unwrap_or_default();
        let derived_fits = derived.get("fits").and_then(|v| v.as_array()).cloned().unwrap_or_default();
        let only_in_disk: Vec<&Value> = on_disk_fits.iter().filter(|v| !derived_fits.contains(v)).collect();
        let only_in_derived: Vec<&Value> = derived_fits.iter().filter(|v| !on_disk_fits.contains(v)).collect();
        panic!(
            "comparison/manifest.json drifted from registry-derived manifest.\n\n\
             only in manifest.json ({}):\n{}\n\n\
             only in registry-derived ({}):\n{}\n\n\
             To fix: cargo run --release --example compare_rust",
            only_in_disk.len(),
            serde_json::to_string_pretty(&only_in_disk).unwrap_or_default(),
            only_in_derived.len(),
            serde_json::to_string_pretty(&only_in_derived).unwrap_or_default(),
        );
    }
}

/// Walk a `tests/fixtures/<dir>/` and collect every `*.json` that is *not*
/// itself a `*.provenance.json` sibling.
fn golden_jsons(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if !dir.is_dir() {
        return out;
    }
    for entry in fs::read_dir(dir).expect("read fixture dir").flatten() {
        let path = entry.path();
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        if !name.ends_with(".json") || name.ends_with(".provenance.json") {
            continue;
        }
        out.push(path);
    }
    out.sort();
    out
}

/// Every JSON golden under `tests/fixtures/{compiler_contract,parity}/`
/// must have a sibling `<stem>.provenance.json`. Phase 4 of the
/// fixture-unification plan: regeneration provenance is required for
/// every checked-in fixture.
///
/// To fix on a fresh checkout: run
/// `cargo run --example backfill_fixture_provenance`. To refresh a
/// specific golden: delete its provenance file and re-run the
/// regenerator command recorded in the *other* siblings provenance.
#[test]
fn every_golden_has_provenance_sibling() {
    let dirs = [
        repo_root().join("tests/fixtures/compiler_contract"),
        repo_root().join("tests/fixtures/parity"),
    ];

    let mut missing: Vec<PathBuf> = Vec::new();
    let mut malformed: Vec<(PathBuf, String)> = Vec::new();
    for dir in &dirs {
        for golden in golden_jsons(dir) {
            let stem = golden
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("UTF-8 stem");
            let prov = golden.with_file_name(format!("{stem}.provenance.json"));
            if !prov.is_file() {
                missing.push(golden);
                continue;
            }
            // Cheap shape check — must parse and carry schema_version.
            match fs::read_to_string(&prov)
                .ok()
                .and_then(|t| serde_json::from_str::<Value>(&t).ok())
            {
                Some(v) if v.get("schema_version").is_some() => {}
                Some(_) => malformed.push((prov, "missing `schema_version`".into())),
                None => malformed.push((prov, "not valid JSON".into())),
            }
        }
    }

    if !missing.is_empty() || !malformed.is_empty() {
        let missing_list = missing
            .iter()
            .map(|p| format!("  - {}", p.display()))
            .collect::<Vec<_>>()
            .join("\n");
        let malformed_list = malformed
            .iter()
            .map(|(p, why)| format!("  - {} ({why})", p.display()))
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "fixture provenance hygiene failed.\n\n\
             missing provenance siblings ({}):\n{}\n\n\
             malformed provenance files ({}):\n{}\n\n\
             To fix: cargo run --example backfill_fixture_provenance",
            missing.len(),
            missing_list,
            malformed.len(),
            malformed_list,
        );
    }
}
