#![cfg(feature = "unstable-internals")]
//! Hygiene checks across the fixture / dataset catalog.
//!
//! Phase 2: comparison/manifest.json must equal the registry-derived view.
//! Phase 4: every JSON golden under tests/fixtures/{compiler_contract,parity}/
//!          must have a sibling `<stem>.provenance.json`.
//! Phase 5: schema/levels lints + opt-in re-fit tolerance check.
//!
//! When the manifest test fails, regenerate via:
//!     cargo run --release --example compare_rust
//!
//! When the provenance test fails on a fresh checkout (no goldens regenerated yet):
//!     cargo run --example backfill_fixture_provenance

use std::fs;
use std::path::{Path, PathBuf};

use mixeff_rs::datasets;
use mixeff_rs::formula::parse_formula;
use mixeff_rs::model::linear::LinearMixedModel;
use mixeff_rs::model::traits::MixedModelFit;
use serde_json::{json, Value};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn comparison_root() -> PathBuf {
    repo_root().join("comparison")
}

/// Build the manifest JSON exactly as `examples/compare_rust.rs` writes it.
/// Keep this in sync with the writer: any change there must mirror here.
fn derived_manifest() -> Value {
    let fits: Vec<Value> = datasets::iter_cases()
        .map(|case| {
            json!({
                "dataset": case.name,
                "estimator": case.fit.estimator,
                "family": case.fit.family,
                "formula": case.fit.formula,
                "link": case.fit.link,
                "weights": case.fit.weights,
            })
        })
        .collect();
    json!({ "fits": fits })
}

#[test]
fn comparison_manifest_matches_registry_derived() {
    let manifest_path = comparison_root().join("manifest.json");
    if !manifest_path.exists() {
        // Manifest is regenerated by `compare_rust`. If it's absent (e.g. on a
        // fresh checkout where the example was never run), the test is a no-op
        // — derivation correctness is still asserted by the unit tests on
        // `iter_cases`. Fail visibly so a CI runner notices the gap rather
        // than silently skipping.
        panic!(
            "comparison/manifest.json missing — run `cargo run --release --example compare_rust` to regenerate"
        );
    }
    let on_disk: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path)
            .unwrap_or_else(|e| panic!("read {manifest_path:?}: {e}")),
    )
    .expect("parse manifest.json");

    let derived = derived_manifest();

    if on_disk != derived {
        // Show a focused diff of the `fits` arrays so the failure message is
        // actionable. The full JSON would be a wall of text.
        let on_disk_fits = on_disk
            .get("fits")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();
        let derived_fits = derived
            .get("fits")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();
        let only_in_disk: Vec<&Value> = on_disk_fits
            .iter()
            .filter(|v| !derived_fits.contains(v))
            .collect();
        let only_in_derived: Vec<&Value> = derived_fits
            .iter()
            .filter(|v| !on_disk_fits.contains(v))
            .collect();
        panic!(
            "comparison/manifest.json drifted from registry-derived manifest.\n\n\
             only in manifest.json ({}):\n{}\n\n\
             only in registry-derived ({}):\n{}\n\n\
             To fix: cargo run --release --example compare_rust",
            only_in_disk.len(),
            serde_json::to_string_pretty(&only_in_disk).unwrap_or_default(),
            only_in_derived.len(),
            serde_json::to_string_pretty(&only_in_derived).unwrap_or_default(),
        );
    }
}

/// CSV header must declare every column in `meta.toml::[[columns]]`.
/// (Extra CSV columns are tolerated — some upstreams emit indices we
/// don't model. This catches the dropped-column case where meta.toml
/// claims a column the CSV doesn't have.)
#[test]
fn csv_header_contains_every_declared_column() {
    for meta in datasets::iter() {
        let name = &meta.name;
        let csv_path = datasets::datasets_root().join(name).join("data.csv");
        let text = fs::read_to_string(&csv_path)
            .unwrap_or_else(|e| panic!("{name}: read {csv_path:?}: {e}"));
        let header_line = text
            .lines()
            .next()
            .unwrap_or_else(|| panic!("{name}: empty data.csv"));
        let headers: Vec<&str> = header_line
            .split(',')
            .map(|s| s.trim().trim_matches('"'))
            .collect();
        for col in &meta.columns {
            assert!(
                headers.iter().any(|h| *h == col.name),
                "{name}: meta.toml declares column `{}` but CSV header is {:?}",
                col.name,
                headers
            );
        }
    }
}

/// Cross-check `_levels.txt` against `meta.toml::[[columns]].levels`.
/// `_levels.txt` is written by the dump scripts; meta.toml is hand-curated.
/// They must agree level-for-level so any future re-dump that reorders
/// factor levels surfaces in the diff rather than silently changing
/// canonical contrast coding.
#[test]
fn levels_txt_matches_meta_levels() {
    use mixeff_rs::datasets::ColumnType;

    for meta in datasets::iter() {
        let name = &meta.name;
        let levels_path = datasets::datasets_root().join(name).join("_levels.txt");
        if !levels_path.is_file() {
            // _levels.txt is optional per REGISTRY.md, but if absent the
            // dataset must declare every categorical levels block in meta.
            for col in &meta.columns {
                if matches!(col.kind, ColumnType::Categorical) {
                    assert!(
                        col.levels.is_some(),
                        "{name}: column `{}` is categorical, has no _levels.txt, and no `levels` declared in meta.toml",
                        col.name
                    );
                }
            }
            continue;
        }

        let text = fs::read_to_string(&levels_path).unwrap();
        let mut from_file: std::collections::HashMap<String, Vec<String>> =
            std::collections::HashMap::new();
        for line in text.lines() {
            // Format: "<column>: <level1>,<level2>,..."
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if let Some((col, rest)) = line.split_once(':') {
                let levels: Vec<String> = rest
                    .trim()
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .collect();
                from_file.insert(col.trim().to_string(), levels);
            }
        }

        for col in &meta.columns {
            if !matches!(col.kind, ColumnType::Categorical) {
                continue;
            }
            // meta.toml may deliberately omit `levels` for high-cardinality
            // factors (e.g. per-observation IDs); that's a valid choice.
            // We only assert here when both sides declare an order — that's
            // where drift between dump scripts and hand-edited meta surfaces.
            let Some(declared) = &col.levels else {
                continue;
            };
            let from_file_levels = match from_file.get(&col.name) {
                Some(v) => v,
                None => continue, // not in _levels.txt — skip (some upstream sources don't dump it)
            };
            assert_eq!(
                declared, from_file_levels,
                "{name}: column `{}` levels mismatch.\n  meta.toml:  {:?}\n  _levels.txt: {:?}",
                col.name, declared, from_file_levels
            );
        }
    }
}

/// Walk a `tests/fixtures/<dir>/` and collect every `*.json` that is *not*
/// itself a `*.provenance.json` sibling.
fn golden_jsons(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if !dir.is_dir() {
        return out;
    }
    for entry in fs::read_dir(dir).expect("read fixture dir").flatten() {
        let path = entry.path();
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        if !name.ends_with(".json") || name.ends_with(".provenance.json") {
            continue;
        }
        out.push(path);
    }
    out.sort();
    out
}

/// Every JSON golden under `tests/fixtures/{compiler_contract,parity}/`
/// must have a sibling `<stem>.provenance.json`. Phase 4 of the
/// fixture-unification plan: regeneration provenance is required for
/// every checked-in fixture.
///
/// To fix on a fresh checkout: run
/// `cargo run --example backfill_fixture_provenance`. To refresh a
/// specific golden: delete its provenance file and re-run the
/// regenerator command recorded in the *other* siblings provenance.
#[test]
fn every_golden_has_provenance_sibling() {
    let dirs = [
        repo_root().join("tests/fixtures/compiler_contract"),
        repo_root().join("tests/fixtures/parity"),
    ];

    let mut missing: Vec<PathBuf> = Vec::new();
    let mut malformed: Vec<(PathBuf, String)> = Vec::new();
    for dir in &dirs {
        for golden in golden_jsons(dir) {
            let stem = golden
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("UTF-8 stem");
            let prov = golden.with_file_name(format!("{stem}.provenance.json"));
            if !prov.is_file() {
                missing.push(golden);
                continue;
            }
            // Cheap shape check — must parse and carry schema_version.
            match fs::read_to_string(&prov)
                .ok()
                .and_then(|t| serde_json::from_str::<Value>(&t).ok())
            {
                Some(v) if v.get("schema_version").is_some() => {}
                Some(_) => malformed.push((prov, "missing `schema_version`".into())),
                None => malformed.push((prov, "not valid JSON".into())),
            }
        }
    }

    if !missing.is_empty() || !malformed.is_empty() {
        let missing_list = missing
            .iter()
            .map(|p| format!("  - {}", p.display()))
            .collect::<Vec<_>>()
            .join("\n");
        let malformed_list = malformed
            .iter()
            .map(|(p, why)| format!("  - {} ({why})", p.display()))
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "fixture provenance hygiene failed.\n\n\
             missing provenance siblings ({}):\n{}\n\n\
             malformed provenance files ({}):\n{}\n\n\
             To fix: cargo run --example backfill_fixture_provenance",
            missing.len(),
            missing_list,
            malformed.len(),
            malformed_list,
        );
    }
}

/// Tolerance config for the re-fit hygiene check. Values come from the
/// Phase 5 mote (bd-01KQMZX24V1S8T12HTAWWV95QY) acceptance criteria.
struct Tolerance {
    beta_rel: f64,
    beta_abs: f64,
    sigma_rel: f64,
    /// Absolute floor for σ — near-zero σ values (boundary fits with
    /// σ → 0) would otherwise fail any relative comparison.
    sigma_abs: f64,
    theta_rel: f64,
    /// Absolute floor for θ — same reasoning as sigma_abs.
    theta_abs: f64,
    objective_abs: f64,
}

impl Default for Tolerance {
    fn default() -> Self {
        Tolerance {
            beta_rel: 1e-4,
            beta_abs: 1e-6,
            sigma_rel: 1e-3,
            sigma_abs: 1e-5,
            theta_rel: 1e-3,
            theta_abs: 1e-5,
            objective_abs: 1e-3,
        }
    }
}

fn approx_equal(actual: f64, expected: f64, abs_tol: f64, rel_tol: f64) -> bool {
    let diff = (actual - expected).abs();
    diff <= abs_tol || diff <= rel_tol * expected.abs()
}

/// Re-fit every pinned `[fits.expected]` block via the in-crate engine and
/// assert β / σ / θ / objective fall within tolerance of the lme4 /
/// MixedModels.jl reference values.
///
/// **Opt-in.** Set `MIXEDMODELS_ENABLE_REFIT_HYGIENE=1` to run. Default
/// behavior is to early-return so the test does not false-flag in-flight
/// numerical work in `src/model/linear.rs`. Once that work has stabilized
/// and the test passes consistently, this gate can be removed.
///
/// Skips: non-Gaussian/Identity fits, `difficulty == "stress"` fixtures
/// (unless `MIXEDMODELS_INCLUDE_STRESS=1`), and pinned fits without an
/// `[fits.expected]` block. Singular fixtures only check
/// `objective` + `is_singular`; θ is non-unique on the boundary.
#[test]
fn every_pinned_fit_matches_within_tolerance() {
    if std::env::var("MIXEDMODELS_ENABLE_REFIT_HYGIENE").is_err() {
        eprintln!(
            "skipped: set MIXEDMODELS_ENABLE_REFIT_HYGIENE=1 to enable the \
             re-fit tolerance hygiene check"
        );
        return;
    }
    let include_stress = std::env::var("MIXEDMODELS_INCLUDE_STRESS").is_ok();
    let tol = Tolerance::default();

    let mut failures: Vec<String> = Vec::new();
    let mut checked = 0usize;
    let mut skipped_glmm = 0usize;
    let mut skipped_stress = 0usize;
    let mut skipped_no_expected = 0usize;

    for case in datasets::iter_cases() {
        let mixeff_rs::datasets::Case {
            name, meta, fit, ..
        } = case;

        let Some(expected) = fit.expected.as_ref() else {
            skipped_no_expected += 1;
            continue;
        };
        if !fit.family.eq_ignore_ascii_case("Gaussian")
            || !fit.link.eq_ignore_ascii_case("Identity")
        {
            skipped_glmm += 1;
            continue;
        }
        let is_stress = meta.tags.difficulty.as_deref() == Some("stress");
        if is_stress && !include_stress {
            skipped_stress += 1;
            continue;
        }

        let reml = match fit.estimator.to_ascii_uppercase().as_str() {
            "REML" => true,
            "ML" => false,
            other => {
                failures.push(format!(
                    "{name} :: {} ({}): unknown estimator `{other}`",
                    fit.formula, fit.estimator
                ));
                continue;
            }
        };

        let (df, _) = match datasets::load(&name) {
            Ok(loaded) => loaded,
            Err(e) => {
                failures.push(format!("{name}: load failed: {e}"));
                continue;
            }
        };
        let formula = match parse_formula(&fit.formula) {
            Ok(f) => f,
            Err(e) => {
                failures.push(format!(
                    "{name} :: {}: formula parse failed: {e}",
                    fit.formula
                ));
                continue;
            }
        };
        let mut model = match LinearMixedModel::new(formula, &df, None) {
            Ok(m) => m,
            Err(e) => {
                failures.push(format!(
                    "{name} :: {}: model construction failed: {e}",
                    fit.formula
                ));
                continue;
            }
        };
        if let Err(e) = model.fit(reml) {
            failures.push(format!("{name} :: {}: fit failed: {e}", fit.formula));
            continue;
        }

        let expected_singular = expected.is_singular.unwrap_or(false);

        if let Some(want_obj) = expected.objective {
            let got_obj = model.objective_value();
            if !approx_equal(got_obj, want_obj, tol.objective_abs, 0.0) {
                failures.push(format!(
                    "{name} :: {} ({}): objective {} drift > {} (expected {})",
                    fit.formula, fit.estimator, got_obj, tol.objective_abs, want_obj
                ));
            }
        }

        if expected_singular {
            let got_singular = MixedModelFit::is_singular(&model);
            if !got_singular {
                failures.push(format!(
                    "{name} :: {} ({}): expected is_singular=true, got false",
                    fit.formula, fit.estimator
                ));
            }
            checked += 1;
            continue;
        }

        if let Some(want_beta) = expected.beta.as_ref() {
            let got_beta: Vec<f64> = MixedModelFit::coef(&model).iter().copied().collect();
            if got_beta.len() != want_beta.len() {
                failures.push(format!(
                    "{name} :: {} ({}): β length {} ≠ expected {}",
                    fit.formula,
                    fit.estimator,
                    got_beta.len(),
                    want_beta.len()
                ));
            } else {
                for (i, (g, w)) in got_beta.iter().zip(want_beta.iter()).enumerate() {
                    if !approx_equal(*g, *w, tol.beta_abs, tol.beta_rel) {
                        failures.push(format!(
                            "{name} :: {} ({}): β[{i}] {g} ≠ expected {w} \
                             (rel {:.1e}, abs floor {:.1e})",
                            fit.formula, fit.estimator, tol.beta_rel, tol.beta_abs
                        ));
                    }
                }
            }
        }

        if let Some(want_sigma) = expected.sigma {
            let got_sigma = model.sigma();
            if !approx_equal(got_sigma, want_sigma, tol.sigma_abs, tol.sigma_rel) {
                failures.push(format!(
                    "{name} :: {} ({}): σ {got_sigma} drift > {:.1e}rel (expected {want_sigma})",
                    fit.formula, fit.estimator, tol.sigma_rel
                ));
            }
        }

        if let Some(want_theta) = expected.theta.as_ref() {
            let got_theta: Vec<f64> = model.theta().to_vec();
            if got_theta.len() == want_theta.len() {
                for (i, (g, w)) in got_theta.iter().zip(want_theta.iter()).enumerate() {
                    if !approx_equal(*g, *w, tol.theta_abs, tol.theta_rel) {
                        failures.push(format!(
                            "{name} :: {} ({}): θ[{i}] {g} drift > {:.1e}rel (expected {w})",
                            fit.formula, fit.estimator, tol.theta_rel
                        ));
                    }
                }
            } else {
                failures.push(format!(
                    "{name} :: {} ({}): θ length {} ≠ expected {}",
                    fit.formula,
                    fit.estimator,
                    got_theta.len(),
                    want_theta.len()
                ));
            }
        }

        checked += 1;
    }

    eprintln!(
        "re-fit hygiene: checked {checked}, skipped (GLMM) {skipped_glmm}, \
         skipped (stress) {skipped_stress}, skipped (no expected) {skipped_no_expected}"
    );

    if !failures.is_empty() {
        let body = failures
            .iter()
            .map(|s| format!("  - {s}"))
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "re-fit hygiene check failed for {} fits:\n{body}\n\n\
             A failure here means one of three things:\n\
              1. Engine drift — the in-crate fit changed numerically. \
                 Compare against `comparison/REPORT.md` to see if the \
                 in-crate vs lme4 delta has shifted.\n\
              2. Fixture drift — `bash scripts/regenerate_all.sh` to refresh \
                 the pinned references against the current reference engine.\n\
              3. Reference engine version drift — lme4 / MixedModels.jl \
                 produces different output now. Bump versions in the \
                 `[provenance]` blocks and refresh.",
            failures.len()
        );
    }
}
