suppressPackageStartupMessages({
  library(lme4)
  library(jsonlite)
})

script_path <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])
if (is.na(script_path) || !nzchar(script_path)) {
  script_path <- file.path("scripts", "regenerate_lme4_glmm_link_fixtures.R")
}

repo_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = FALSE)
if (!dir.exists(file.path(repo_root, "tests"))) {
  repo_root <- normalizePath(getwd(), mustWork = TRUE)
}

group_effects <- c(-0.55, -0.25, 0.0, 0.22, 0.48, 0.12, -0.38, 0.34)

binary_case <- function(id, link, intercept, slope) {
  y <- numeric()
  trials <- numeric()
  x <- numeric()
  group <- character()
  successes <- numeric()
  for (g in seq_along(group_effects)) {
    for (obs in 0:5) {
      xv <- obs - 2.5
      eta <- intercept + slope * xv + group_effects[[g]]
      p <- switch(link,
        probit = stats::pnorm(eta),
        cloglog = -expm1(-exp(eta)),
        stop("unknown binary link")
      )
      n <- 12 + ((g + obs) %% 5)
      wiggle <- ((2 * g + obs) %% 3) - 1
      k <- min(n, max(0, round(n * p + wiggle)))
      y <- c(y, k / n)
      trials <- c(trials, n)
      successes <- c(successes, k)
      x <- c(x, xv)
      group <- c(group, sprintf("g%d", g))
    }
  }

  df <- data.frame(
    y = y,
    successes = successes,
    failures = trials - successes,
    trials = trials,
    x = x,
    group = factor(group, levels = sprintf("g%d", seq_along(group_effects)))
  )
  fit <- glmer(
    cbind(successes, failures) ~ 1 + x + (1 | group),
    data = df,
    family = stats::binomial(link = link),
    nAGQ = 1,
    control = glmerControl(optimizer = "bobyqa", calc.derivs = FALSE)
  )

  list(
    id = id,
    family = "binomial",
    link = link,
    formula = "y ~ 1 + x + (1 | group)",
    n_agq = 1,
    y = unname(y),
    weights = unname(trials),
    x = unname(x),
    group = unname(group),
    lme4 = fit_reference(fit)
  )
}

poisson_sqrt_case <- function() {
  y <- numeric()
  x <- numeric()
  group <- character()
  for (g in seq_along(group_effects)) {
    for (obs in 0:6) {
      xv <- obs - 3.0
      eta <- 1.45 + 0.12 * xv + 0.9 * group_effects[[g]]
      mu <- eta^2
      count <- max(0, round(mu + ((g + 2 * obs) %% 4) * 0.25))
      y <- c(y, count)
      x <- c(x, xv)
      group <- c(group, sprintf("g%d", g))
    }
  }

  df <- data.frame(
    y = y,
    x = x,
    group = factor(group, levels = sprintf("g%d", seq_along(group_effects)))
  )
  fit <- glmer(
    y ~ 1 + x + (1 | group),
    data = df,
    family = stats::poisson(link = "sqrt"),
    nAGQ = 1,
    control = glmerControl(optimizer = "bobyqa", calc.derivs = FALSE)
  )

  list(
    id = "poisson_sqrt",
    family = "poisson",
    link = "sqrt",
    formula = "y ~ 1 + x + (1 | group)",
    n_agq = 1,
    y = unname(y),
    weights = NULL,
    x = unname(x),
    group = unname(group),
    lme4 = fit_reference(fit)
  )
}

fit_reference <- function(fit) {
  list(
    engine = "lme4::glmer",
    version = sprintf("lme4 %s; R %s", as.character(packageVersion("lme4")), getRversion()),
    status = "fit",
    beta = as.list(unname(as.numeric(fixef(fit)))),
    theta = as.list(unname(as.numeric(getME(fit, "theta")))),
    objective = unname(as.numeric(-2 * logLik(fit))),
    deviance = unname(as.numeric(deviance(fit))),
    loglik = unname(as.numeric(logLik(fit))),
    aic = unname(as.numeric(AIC(fit))),
    bic = unname(as.numeric(BIC(fit))),
    fitted_mu_head = as.list(unname(as.numeric(head(fitted(fit), 8)))),
    is_singular = isTRUE(isSingular(fit, tol = 1e-4))
  )
}

payload <- list(
  schema_version = "1.0.0",
  source = sprintf("lme4 GLMM link fixtures generated by %s", basename(script_path)),
  cases = list(
    binary_case("binomial_probit", "probit", -0.35, 0.32),
    binary_case("binomial_cloglog", "cloglog", -0.75, 0.28),
    poisson_sqrt_case()
  )
)

out_path <- file.path(repo_root, "tests", "fixtures", "parity", "glmm_link_lme4.json")
dir.create(dirname(out_path), recursive = TRUE, showWarnings = FALSE)
write_json(payload, out_path, auto_unbox = TRUE, pretty = TRUE, digits = NA, null = "null")
commit <- tryCatch(
  system2("git", c("-C", repo_root, "rev-parse", "HEAD"), stdout = TRUE, stderr = FALSE)[1],
  error = function(e) NA_character_
)
provenance <- list(
  schema_version = "1.0",
  generated_at = format(as.POSIXct(Sys.time(), tz = "UTC"), "%Y-%m-%dT%H:%M:%SZ"),
  crate_commit = if (is.na(commit)) NULL else commit,
  regenerator = "scripts/regenerate_lme4_glmm_link_fixtures.R",
  source_case = NULL,
  reference_engine = sprintf("lme4 %s", as.character(packageVersion("lme4"))),
  notes = sprintf(
    "R %s; deterministic binomial-probit, binomial-cloglog, and poisson-sqrt GLMM fixtures",
    getRversion()
  )
)
write_json(
  provenance,
  sub("\\.json$", ".provenance.json", out_path),
  auto_unbox = TRUE,
  pretty = TRUE,
  null = "null"
)
cat(out_path, "\n")
